### ISSUE TITLE
climbing

### ISSUE THREAD

**Issue by xyfighter** [Max-and-Duke/Max-and-Duke#1]
while climbing on ladders, cannot go through other objects like boards

**Comment by AugustusZ** [comment]
According to [this](http://answers.unity3d.com/answers/765311/view.html) and inspired by [this](http://answers.unity3d.com/answers/41724/view.html), a QUICK solution could be: 
1. split a ladder into several parts (children game objects) and add detection (e.g. a collider w/ isTrigger == True) for each part
2. when a play when a player is inside of the green area with a key **Down** pressed, tele-transport it to red area. See the illustration below.

<img width="242" alt="screen shot 2016-09-19 at 11 38 35 pm" src="https://cloud.githubusercontent.com/assets/8922602/18659895/4aed6ffc-7ec2-11e6-955d-8d57e3bfd6ff.png">

**Comment by xyfighter** [comment]
change the function into update() and instead of changing velocity, change transform.position
